"""Atualizar modelos e relacionamentos

Revision ID: 7ce51b884163
Revises: ca3d1e21e58b
Create Date: 2024-07-19 15:22:36.068286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce51b884163'
down_revision: Union[str, None] = 'ca3d1e21e58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
