"""Add fornecedor_id to encomendas

Revision ID: 875542a5bca7
Revises: 7ce51b884163
Create Date: 2024-07-22 17:07:08.800076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875542a5bca7'
down_revision: Union[str, None] = '7ce51b884163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encomendas', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'encomendas', 'fornecedores', ['fornecedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encomendas', type_='foreignkey')
    op.drop_column('encomendas', 'fornecedor_id')
    # ### end Alembic commands ###
