"""cria tabelas distribuidora

Revision ID: ca3d1e21e58b
Revises: 
Create Date: 2024-07-19 15:05:54.899013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3d1e21e58b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('status_atividade', sa.Boolean(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status_ativo', sa.Boolean(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motoristas_cpf'), 'motoristas', ['cpf'], unique=True)
    op.create_index(op.f('ix_motoristas_id'), 'motoristas', ['id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('status_ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_table('encomendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('prazo_entrega', sa.DateTime(), nullable=True),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('status_encomenda', sa.Boolean(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encomendas_id'), 'encomendas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encomendas_id'), table_name='encomendas')
    op.drop_table('encomendas')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_motoristas_id'), table_name='motoristas')
    op.drop_index(op.f('ix_motoristas_cpf'), table_name='motoristas')
    op.drop_table('motoristas')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
