"""Update tables and entities

Revision ID: d0228e2157ee
Revises: 875542a5bca7
Create Date: 2024-07-23 14:41:38.467615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0228e2157ee'
down_revision: Union[str, None] = '875542a5bca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('encomenda_produto',
    sa.Column('encomenda_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encomenda_id'], ['encomendas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], )
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encomenda_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encomenda_id'], ['encomendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.add_column('clientes', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_fornecedores_email'), 'fornecedores', ['email'], unique=True)
    op.create_index(op.f('ix_motoristas_email'), 'motoristas', ['email'], unique=True)
    op.alter_column('veiculos', 'ano',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('veiculos', 'ano',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_motoristas_email'), table_name='motoristas')
    op.drop_index(op.f('ix_fornecedores_email'), table_name='fornecedores')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_column('clientes', 'email')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_table('encomenda_produto')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
