"""Add email to cliente

Revision ID: f415f0d2aa8f
Revises: d0228e2157ee
Create Date: 2024-07-23 14:48:19.876250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f415f0d2aa8f'
down_revision: Union[str, None] = 'd0228e2157ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
